### ISSUE TITLE
Allow arbitrary php.ini settings

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox-engine-php#20]
Currently a selected set of php.ini settings can be customized by [settings](http://guides.nanobox.io/php/php-settings/).

However, this can never cover all cases and also must be updated as soon as a new PHP version is released.

Thus I'd suggest a ways to pass arbitrary php.ini settings to the built containers.

Here is an example how this could look like in the [puppet-php module](https://github.com/voxpupuli/puppet-php#alternative-examples-using-hiera).

**Comment by tylerflint** [comment]
@notxarb I like this. What do you think?

**Comment by notxarb** [comment]
Another option would be to utilize the php.d directory.

**Comment by mbrodala** [comment]
@notxarb Better late than nothing: yes this is what I came up with now: https://github.com/nanobox-io/nanobox/issues/653
