### ISSUE TITLE
Add phpdbg package

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox-engine-php#36]
The [phpdbg](http://phpdbg.com/) package should be added for debugging and code coverage reporting.

**Comment by notxarb** [comment]
phpdbg should be available with the php 7.0 and 7.1 packages, and now the php 5.6

**Comment by mbrodala** [comment]
Thanks, what is the package name? I cannot see anything in the [pkgsrc](http://pkgsrc.nanobox.io/nanobox/base/Linux/). I tried `phpdbg` but only got an error.

**Comment by notxarb** [comment]
It looks like the phpdbg interactive debugger is [distributed with php 5.6 and newer](http://php.net/manual/en/debugger-about.php). It should be part of the base php package. Yesterday I recompiled the php 5.6 package and added the phpdbg in the build.

**Comment by mbrodala** [comment]
Indeed, it's there, thanks!
