### ISSUE TITLE
sqlite3 extension

### ISSUE THREAD

**Issue by geekish** [nanobox-io/nanobox-engine-php#40]
It looks like PHP is being built `--without-sqlite3`... is there a good reason for this?
I am trying to use Nanobox in a project that requires it.

I should note that `sqlite3` is not the same as the `sqlite` or `pdo_sqlite` extensions.

**Comment by danhunsaker** [comment]
Other than minimizing the amount of stuff that's built in so as to keep things small and fast?  Most projects don't use SQLite, especially with Nanobox's DB design.

**Comment by geekish** [comment]
I understand why. I guess I asked the wrong question.
Can `sqlite3` be added as an available extension?

For what it's worth... I'm trying to demo [Canvas](https://github.com/cnvs/canvas); they use [TNTSearch](https://github.com/teamtnt/tntsearch/) which requires the extension.

**Comment by sanderson** [comment]
@geekish I'll add it to the list of extensions to compile. As long as it compiles correctly, I don't know of a reason it couldn't be made available.

**Comment by tylerflint** [comment]
Hi @geekish, that makes sense. That should be made available as an extension. In theory, everything that gets stripped out of php should be made available as an extension. Thanks for the heads up.

**Comment by geekish** [comment]
@sanderson Thanks!

@tylerflint I think it might help to also document somewhere what is and isn't included in the base build.

**Comment by tylerflint** [comment]
That's a great idea. As a point of reference, here are the configure args for php 7:

https://github.com/nanobox-io/nanobox-pkgsrc-base/blob/master/php70/Makefile.php#L33-L54

**Comment by geekish** [comment]
@tylerflint Awesome, that does help!
