### ISSUE TITLE
Arbitrary configuration for web servers

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox-engine-php#41]
_From @mbrodala on December 20, 2016 8:50_

Currently the configuration for Apache, Nginx and e.g. PHP builtin is limited to a few selected options.

Since this can never cover all use cases the system should be changed to allow either for arbitrary options or to be able to specify a configuration file to include.

_Copied from original issue: nanobox-io/nanobox#308_

**Comment by danhunsaker** [comment]
https://content.nanobox.io/custom-nginx-configs-with-nanobox-php-engine/

**Comment by mbrodala** [comment]
Yep, that's actually a lot easier than introducing a mapping layer in Nanobox. :-)
