### ISSUE TITLE
Extensions not loaded in PHP 7.2

### ISSUE THREAD

**Issue by danhunsaker** [nanobox-io/nanobox-engine-php#64]
When using `runtime: php-7.2`, the extensions aren't loaded, because they never get added to the `php.ini` files. The reason for this is found here:

https://github.com/nanobox-io/nanobox-engine-php/blob/c8e8374906460f6eb75682fc4767bf0ee7bb6247/lib/php/php/general.sh#L273

This line returns the first extensions directory found in `/data/lib/php/`, without checking whether PHP will actually use it at any point, nor whether any extensions are actually present within. In the case of 7.2, there are _two_ extensions directories, one for the `20160731` version of the API, and another for the `20170718` version. The above line returns `20160731`, but all the extensions we actually use are installed in `20170718`, so none of the `.so` files are found, leading to all the extensions being omitted from the `php.ini` files.

We need to figure out how to work around this...

**Comment by danielcosta** [comment]
Maybe we should try something like this?

```bash
for i in /data/lib/php/*; do [[ "$i" =~ /[0-9]+$ ]] && extensions_dir=$i; done; echo $extensions_dir && return
```

**Comment by danhunsaker** [comment]
That would always return the last directory found, which would solve the current scenario, but it's just as brittle as the current approach. What we really need is a way to determine which API version our PHP binary actually expects, and to use _that_ to determine the correct path.

**Comment by notxarb** [comment]
I think this was taken care of by a recent recompile of the php-7.2.0 package
