### ISSUE TITLE
Ignoring deprecated use of DefaultType in line 50 of /data/etc/httpd/httpd.conf.

### ISSUE THREAD

**Issue by k1462015** [nanobox-io/nanobox-engine-php#72]
When running php and apache, I receive the following error
`[Sat Dec 09 16:45:51.543655 2017] [core:warn] ... AH00117: Ignoring deprecated use of DefaultType in line 50 of /data/etc/httpd/httpd.conf.`

**Comment by notxarb** [comment]
This should be fixed now

**Comment by k1462015** [comment]
Yep, thanks.
