### ISSUE TITLE
php.ini set to log on a file not being watched

### ISSUE THREAD

**Issue by fariasf** [nanobox-io/nanobox-engine-php#74]
The default `php.ini` is set to log on `/data/var/log/php/error.log` (https://github.com/nanobox-io/nanobox-engine-php/blob/master/templates/php/php.ini.mustache#L36).

But [`php-server`](https://github.com/nanobox-io/nanobox-engine-php/blob/master/templates/bin/php-server.mustache#L81), and I think the [default `log_watch` value for prod](https://github.com/nanobox-io/nanobox-engine-php/tree/master/templates/boxfile.mustache#L15) (not sure if that's the right file) watch for a different path: `/data/var/log/php/php_error.log`.

As a result, the default behavior ignores the PHP error logs (they are stored, but not displayed to the user unless adding a custom `log_watch` entry to the boxfile for production and starting the servers with a custom command for local development).

**Comment by notxarb** [comment]
This should be fixed now

**Comment by fariasf** [comment]
Thanks! Indeed, PR #76 fixes it. LGTM!
