### ISSUE TITLE
/data/var/log/apache/error.log <== httpd (pid 135) already running

### ISSUE THREAD

**Issue by k1462015** [nanobox-io/nanobox-engine-php#89]
- This is fairly regular issue now
- I have to run `nanobox stop` multiple times (not just once), and then keep running `nanobox run php-server`

**Comment by Istanful** [comment]
Bump. I have this problem as well.

**Comment by bnunamak** [comment]
(I also have this problem)

**Comment by harryfk** [comment]
Same here.

**Comment by bnunamak** [comment]
In my case this was due to an unclean shutdown of apache... For me the quickest fix is `nanobox run`ning into the box and running `php-server` from inside the machine, which gives the following output and then successfully runs the server:

> ==> /data/var/log/apache/error.log <==
>[core:warn] [pid 204:tid 139764049921920] AH00098: pid file /data/var/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
>[mpm_worker:notice] [pid 204:tid 139764049921920] AH00292: Apache/2.4.33 (Unix) configured -- resuming normal operations[Sun Jul 22 12:52:19.844612 2018] [core:notice] [pid 204:tid 139764049921920] AH00094: Command line: '/data/sbin/httpd -D NO_DETACH -c DocumentRoot /app/public -C ProxyPassMatch "^/(.*\\.php(/.*)?)$" "unix:/data/var/tmp/php.sock|fcgi://localhost/app/public"'

**Comment by k1462015** [comment]
I ended up switching to nginx and haven't experienced any issues. I couldn't get nginx working with the options Nanobox exposes so I did need to use a custom nginx.conf file
